services:
  web:
    build: .
    working_dir: /usr/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./
          target: /usr/app
          action: sync